name: Bug report
description: Report a bug or issue with the project
title: "[BUG] "
labels: "bug"
assignees: " "

body:
  - type: markdown
    attributes:
      value: |
        <!--- Provide a general summary of the issue in the Title above -->

  - type: input
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: Describe what you expected to happen
      placeholder: Describe the expected behavior here

  - type: input
    id: current_behavior
    attributes:
      label: Current Behavior
      description: Describe what actually happened
      placeholder: Describe the current behavior here

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce
      description: Provide the steps to reproduce the issue
      placeholder: List the steps to reproduce the issue here

  - type: textarea
    id: possible_solution
    attributes:
      label: Possible Solution
      description: Suggest a fix or reason for the bug
      placeholder: Suggest a possible solution here

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the bug here
      placeholder: Provide additional context here

  - type: input
    id: environment
    attributes:
      label: Your Environment
      description: Include as many relevant details about the environment you experienced the bug in
      placeholder: Describe your environment here