name: Enhancement
description: Suggest an enhancement or improvement for the project
title: "[ENHANCEMENT] "
labels: "enhancement"


body:
  - type: markdown
    attributes:
      value: |
        <!--- Provide a general summary of the enhancement in the Title above -->

  - type: input
    id: current_behavior
    attributes:
      label: Current Behavior
      description: Describe the current behavior of the feature
      placeholder: Describe the current behavior here

  - type: input
    id: suggested_improvement
    attributes:
      label: Suggested Improvement
      description: Describe the improvement you are suggesting
      placeholder: Describe the suggested improvement here

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the enhancement here
      placeholder: Provide additional context here