name: Task
description: Suggest an improvement to the current feature
title: "[TASK] "
labels: "task"


body:
  - type: markdown
    attributes:
      value: |
        <!--- Provide a general summary of the task in the Title above -->

  - type: input
    id: current_behavior
    attributes:
      label: Current Behavior
      description: Describe the current behavior of the feature
      placeholder: Describe the current behavior here

  - type: input
    id: suggested_improvement
    attributes:
      label: Suggested Improvement
      description: Describe the improvement you are suggesting
      placeholder: Describe the suggested improvement here

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the task here
      placeholder: Provide additional context here