name: Feature request
description: Suggest a new feature or enhancement for the project
title: "[FEATURE] "
labels: "enhancement"
assignees: " "

body:
  - type: markdown
    attributes:
      value: |
        <!--- Provide a general summary of the feature in the Title above -->

  - type: input
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: Describe how you expect the feature to work
      placeholder: Describe the expected behavior here

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here
      placeholder: Provide additional context here